# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# =========================================================================
# INSTALLATION NOTE:
# This script requires the following Python libraries installed in your
# environment. Run this command in your terminal:
# pip install numpy PyQt5 joblib scikit-learn
# =========================================================================

from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np 
import joblib 

class Ui_MainWindow(object):
    
    ml_model = None
    ml_features = None 

    def __init__(self):
        super().__init__()
        self.load_model()
        
    def load_model(self):
        """
        Loads the pickled machine learning model (enhanced_cart.pkl) using joblib.
        It expects the file to contain a dictionary with "model" and optionally "features" keys.
        
        NOTE: This function assumes 'enhanced_cart.pkl' is in the current working directory.
        """
        model_filename = 'enhanced_cart.pkl'
        
        try:
            print(f"INFO: Attempting to load ML model ({model_filename}) using joblib...")
            
            # 1. Load the data dictionary from the file using joblib
            data = joblib.load(model_filename)
            
            # 2. Extract model and features
            model_candidate = data.get("model")
            features_candidate = data.get("features")

            if callable(getattr(model_candidate, 'predict', None)):
                Ui_MainWindow.ml_model = model_candidate
                Ui_MainWindow.ml_features = features_candidate 
                print(f"INFO: Model '{model_filename}' loaded successfully. Type: {type(model_candidate)}")
                if Ui_MainWindow.ml_features:
                    print(f"INFO: Model expects {len(Ui_MainWindow.ml_features)} features: {Ui_MainWindow.ml_features}")
                else:
                    print("WARNING: Feature list ('features' key) not found in the loaded file.")

            else:
                print(f"ERROR: Object loaded from PKL file does not have a 'predict' method or 'model' key is missing.")
                print(f"Loaded object type: {type(model_candidate)}. Expected a model object.")
                Ui_MainWindow.ml_model = None
            
        except FileNotFoundError:
            print(f"ERROR: Model file not found: {model_filename}")
            Ui_MainWindow.ml_model = None
        except Exception as e:
            print(f"ERROR: Failed to load ML model from {model_filename}: {e}")
            Ui_MainWindow.ml_model = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.setStyleSheet("\n" "")
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.centralwidget.setContentsMargins(0, 0, 0, 0)
        
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.mainLayout.setContentsMargins(0, 0, 0, 0) 
        self.mainLayout.setSpacing(15)
        self.mainLayout.setObjectName("mainLayout")
        
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        
        self.groupBoxLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.groupBoxLayout.setContentsMargins(10, 30, 10, 10) 
        self.groupBoxLayout.setSpacing(10)
        
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        
        # --- Form Elements Start ---
        self.amount = QtWidgets.QLabel(self.formLayoutWidget)
        self.amount.setObjectName("amount")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.amount)
        self.amount_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.amount_line.setValidator(QtGui.QDoubleValidator())
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amount_line.sizePolicy().hasHeightForWidth())
        self.amount_line.setSizePolicy(sizePolicy)
        self.amount_line.setObjectName("amount_line")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.amount_line)
        
        self.oldbalOrg = QtWidgets.QLabel(self.formLayoutWidget)
        self.oldbalOrg.setObjectName("oldbalOrg")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.oldbalOrg)
        self.oldbalOrg_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.oldbalOrg_line.setValidator(QtGui.QDoubleValidator())
        self.oldbalOrg_line.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.oldbalOrg_line.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.oldbalOrg_line.setObjectName("oldbalOrg_line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.oldbalOrg_line)
        
        self.newbalOrg = QtWidgets.QLabel(self.formLayoutWidget)
        self.newbalOrg.setObjectName("newbalOrg")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.newbalOrg)
        self.newbalOrg_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.newbalOrg_line.setValidator(QtGui.QDoubleValidator())
        self.newbalOrg_line.setObjectName("newbalOrg_line")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.newbalOrg_line)
        
        self.oldbalDest = QtWidgets.QLabel(self.formLayoutWidget)
        self.oldbalDest.setObjectName("oldbalDest")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.oldbalDest)
        self.oldbalDest_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.oldbalDest_line.setValidator(QtGui.QDoubleValidator())
        self.oldbalDest_line.setObjectName("oldbalDest_line")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.oldbalDest_line)
        
        self.newbalDest = QtWidgets.QLabel(self.formLayoutWidget)
        self.newbalDest.setObjectName("newbalDest")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.newbalDest)
        self.newbalDest_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.newbalDest_line.setValidator(QtGui.QDoubleValidator())
        self.newbalDest_line.setText("")
        self.newbalDest_line.setObjectName("newbalDest_line")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.newbalDest_line)
        # --- Form Elements End ---
        
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        
        self.buttonLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.buttonLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.buttonLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        
        self.submitButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.submitButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.submitButton.setObjectName("submitButton")
        self.buttonLayout.addWidget(self.submitButton)
        self.submitButton.setEnabled(False)
        
        self.clearButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.clearButton.setObjectName("clearButton")
        self.buttonLayout.addWidget(self.clearButton)

        self.groupBoxLayout.addWidget(self.formLayoutWidget)
        self.groupBoxLayout.addWidget(self.horizontalLayoutWidget)

        self.mainLayout.addWidget(self.groupBox)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        MainWindow.setFixedSize(MainWindow.sizeHint())
        
        self.submitButton.clicked.connect(self.show_fraud_result) 
        self.clearButton.clicked.connect(self.clear_inputs)
        
        self.amount_line.textChanged.connect(self.validate_inputs)
        self.oldbalOrg_line.textChanged.connect(self.validate_inputs)
        self.newbalOrg_line.textChanged.connect(self.validate_inputs)
        self.oldbalDest_line.textChanged.connect(self.validate_inputs)
        self.newbalDest_line.textChanged.connect(self.validate_inputs)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fraud Detection Transaction Analyzer"))
        self.groupBox.setTitle(_translate("MainWindow", "Enter Transaction Details"))
        self.amount.setText(_translate("MainWindow", "Enter transaction amount:"))
        self.amount_line.setPlaceholderText(_translate("MainWindow", "Enter numerical value"))
        self.oldbalOrg.setText(_translate("MainWindow", "Enter old balance of customer: "))
        self.oldbalOrg_line.setPlaceholderText(_translate("MainWindow", "Enter numerical value"))
        self.newbalOrg.setText(_translate("MainWindow", "Enter new balance of customer: "))
        self.newbalOrg_line.setPlaceholderText(_translate("MainWindow", "Enter numerical value"))
        self.oldbalDest.setText(_translate("MainWindow", "Enter old balance of recipient:"))
        self.oldbalDest_line.setPlaceholderText(_translate("MainWindow", "Enter numerical value"))
        self.newbalDest.setText(_translate("MainWindow", "Enter new balance of recipient:"))
        self.newbalDest_line.setPlaceholderText(_translate("MainWindow", "Enter numerical value"))
        self.submitButton.setText(_translate("MainWindow", "Submit"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))

    def validate_inputs(self):
        """
        Checks if all five required QLineEdit widgets contain non-empty text
        and enables/disables the submit button accordingly.
        """
        input_lines = [
            self.amount_line,
            self.oldbalOrg_line,
            self.newbalOrg_line,
            self.oldbalDest_line,
            self.newbalDest_line
        ]
        
        all_filled = all(line.text().strip() for line in input_lines)
        self.submitButton.setEnabled(all_filled)

    def clear_inputs(self):
        """Resets all QLineEdit widgets to empty strings."""
        self.amount_line.clear()
        self.oldbalOrg_line.clear()
        self.newbalOrg_line.clear()
        self.oldbalDest_line.clear()
        self.newbalDest_line.clear()
        
    def show_fraud_result(self):
        """
        Reads the input fields, uses the ML model to predict fraud, and displays the result. 
        """
        
        # 1. Read input values, converting them to float or 0.0 if empty/invalid
        try:
            amount = float(self.amount_line.text()) if self.amount_line.text() else 0.0
            oldbalOrg = float(self.oldbalOrg_line.text()) if self.oldbalOrg_line.text() else 0.0
            newbalOrg = float(self.newbalOrg_line.text()) if self.newbalOrg_line.text() else 0.0
            oldbalDest = float(self.oldbalDest_line.text()) if self.oldbalDest_line.text() else 0.0
            newbalDest = float(self.newbalDest_line.text()) if self.newbalDest_line.text() else 0.0
        except ValueError:
            error_msg = QtWidgets.QMessageBox()
            error_msg.setWindowTitle("Input Error")
            error_msg.setText("Please enter only valid numerical values.")
            error_msg.setIcon(QtWidgets.QMessageBox.Warning)
            error_msg.exec_()
            return
            
        # 2. Prepare data for the model
        input_data = np.array([[amount, oldbalOrg, newbalOrg, oldbalDest, newbalDest]])
        is_fraudulent = False
        
        # 3. Perform prediction using the loaded model
        if Ui_MainWindow.ml_model is not None:
            try:
                prediction = Ui_MainWindow.ml_model.predict(input_data)
                is_fraudulent = prediction[0] == 1
                
            except Exception as e:
                print(f"CRITICAL ERROR: Model prediction failed: {e}. Cannot proceed without a prediction.")
                error_msg = QtWidgets.QMessageBox()
                error_msg.setWindowTitle("Prediction Error")
                error_msg.setText("Critical error during prediction. Check console for details.")
                error_msg.setIcon(QtWidgets.QMessageBox.Critical)
                error_msg.exec_()
                return 
                
        else:
            print("CRITICAL ERROR: ML model failed to load. Cannot perform prediction.")
            error_msg = QtWidgets.QMessageBox()
            error_msg.setWindowTitle("Model Not Loaded")
            error_msg.setText("The machine learning model is not available. Prediction cannot be performed.")
            error_msg.setIcon(QtWidgets.QMessageBox.Critical)
            error_msg.exec_()
            return 

        # 4. Create the result dialog box (QMessageBox acts as a modal dialog)
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle("Transaction Analysis Result")
        
        if is_fraudulent:
            result_text = "The transaction is FRAUDULENT."
            msg.setText(f"<h3 style='color: #C0392B; font-weight: bold;'>{result_text}</h3>")
            msg.setIcon(QtWidgets.QMessageBox.Critical)
        else:
            result_text = "The transaction appears LEGITIMATE."
            msg.setText(f"<h3 style='color: #27AE60; font-weight: bold;'>{result_text}</h3>")
            msg.setIcon(QtWidgets.QMessageBox.Information)

        informative_text = (
            f"Amount: ₱{amount:,.2f}\n"
            f"Old Balance (Originator): ₱{oldbalOrg:,.2f}\n"
            f"New Balance (Originator): ₱{newbalOrg:,.2f}\n"
            f"Old Balance (Recipient): ₱{oldbalDest:,.2f}\n"
            f"New Balance (Recipient): ₱{newbalDest:,.2f}\n\n"
        )
        msg.setInformativeText(informative_text)
        msg.setStandardButtons(QtWidgets.QMessageBox.Ok)
        
        msg.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
